-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.campaign
(
    cf_id integer NOT NULL,
    contact_id integer NOT NULL,
    company_name character varying(80) COLLATE pg_catalog."default",
    description character varying(80) COLLATE pg_catalog."default",
    goal real,
    pledged real,
    outcome character varying(80) COLLATE pg_catalog."default",
    backers_count integer,
    country character varying(5) COLLATE pg_catalog."default",
    currency character varying(6) COLLATE pg_catalog."default",
    launched_date date,
    end_date date,
    category_id character varying(80) COLLATE pg_catalog."default" NOT NULL,
    subcategory_id character varying(80) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT campaign_pkey PRIMARY KEY (cf_id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.category
(
    category_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    category character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT category_pkey PRIMARY KEY (category_id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.contacts
(
    contact_id integer NOT NULL,
    first_name character varying(50) COLLATE pg_catalog."default",
    last_name character varying(50) COLLATE pg_catalog."default",
    email character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT contacts_pkey PRIMARY KEY (contact_id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.subcategory
(
    subcategory_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    subcategory character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT subcategory_pkey PRIMARY KEY (subcategory_id)
)
WITH (
    OIDS = FALSE
);

ALTER TABLE IF EXISTS public.campaign
    ADD FOREIGN KEY (contact_id)
    REFERENCES public.contacts (contact_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.campaign
    ADD FOREIGN KEY (category_id)
    REFERENCES public.category (category_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.campaign
    ADD FOREIGN KEY (subcategory_id)
    REFERENCES public.subcategory (subcategory_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;